### ISSUE TITLE
Any way to polymorphically accept `float` and `double` attributes?

### ISSUE THREAD

**Issue by ataber** [ddiakopoulos/tinyply#13]
In my application I have to deal with meshes that can have positions of either `float` or `double` length. I've kinda sorta hacked something together by try-catching the error tinyply throws if the attribute isn't the right type, but I'm wondering if there's a better way to do it? Possibly by reading the header and exposing the property types to the client?

**Comment by ddiakopoulos** [comment]
The try-catch was my original intention there, but it should have thrown a custom exception.

Can you check out the 2.0 branch? Instead of typed buffers as the input/output, everything is now treated internally as an untyped byte buffer with property types exposed to the user as metadata.

See: https://github.com/ddiakopoulos/tinyply/blob/2.0/source/example.cpp#L205
